apiVersion: v1
kind: Pod
metadata:
  name: webapi
  namespace: basta-2020
  labels:
    app: webapi
    city: Mainz
    environment: development
    kind: backend
spec:
  containers:
    - name: api
      image: thorstenhans/kubernetes-workshop:0.0.2
      ports:
        - containerPort: 80
