apiVersion: v1
kind: Pod
metadata:
  name: webapi
  namespace: basta-2020
spec:
  containers:
    - name: api
      image: thorstenhans/kubernetes-workshop:0.0.2
      ports:
        - containerPort: 80
