apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapi-deployment
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapi-deployment
  targetCPUUtilizationPercentage: 60
