apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapi
    city: Mainz
    environment: development
  name: webapi-deployment
  namespace: basta-2020-deployments
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapi
      environment: development
      kind: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: webapi
        city: Mainz
        environment: development
        kind: backend
    spec:
      containers:
        - image: thorstenhans/kubernetes-workshop:0.0.2
          name: api
          env:
            # 1. manuelle Wertevergabe
            - name: BASTA_DAY
              value: Friday
            # 2. 1. Wert aus ConfigMap laden
            - name: API_COMPRESSION_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  key: api.config.compression
                  name: basta-2020-config-2
            - name: CONNECTIONSTRINGS__DB
              valueFrom:
                secretKeyRef:
                  key: ConnectionString
                  name: dev-db-connection-string
          # 3 alle Werte einer ConfigMap laden
          envFrom:
            - configMapRef:
                name: basta-2020-config-1
          ports:
            - containerPort: 80
          resources: {}
