apiVersion: v1
kind: Namespace
metadata:
  name: basta-2020
---
apiVersion: v1
kind: Namespace
metadata:
  name: basta-2020-deployments
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
